### ISSUE TITLE
Error while executing 'npm run seed'

### ISSUE THREAD

**Issue by ajtesters** [open-source-labs/dbSpy#127]
Pulled the latest source code for running in dev environment. Experienced the following error

npm run seed

> dbspy@6.0.1 seed
> ts-node ./server/seed/seed.ts

D:\dev\repos\dbSpy\node_modules\ts-node\src\index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
server/seed/seed.ts:6:22 - error TS2307: Cannot find module '../entities/user.entity' or its corresponding type declarations.

6 import { User } from '../entities/user.entity'
                       ~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (D:\dev\repos\dbSpy\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (D:\dev\repos\dbSpy\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (D:\dev\repos\dbSpy\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (D:\dev\repos\dbSpy\node_modules\ts-node\src\index.ts:1433:41)
    at Module.m._compile (D:\dev\repos\dbSpy\node_modules\ts-node\src\index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Object.require.extensions.<computed> [as .ts] (D:\dev\repos\dbSpy\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
  diagnosticCodes: [ 2307 ]
}

**Comment by sidoelz123** [comment]
maybe you can use branch 4.1
